### PR TITLE
update tfsec step to run brew install as ubuntu user

### PR DESCRIPTION
**Pull request by davidlawson83**
Updating the tfsec step to use the ubuntu user to run 'brew install tfsec' as it's no longer allowed to be run as root. 

For reference - "Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system."

### CODE REVIEW

**Comment by dominicbr** [comment]
Looks like there's still a problem running tfsec: https://github.com/infinitytracking/platform-apiweb-servers/actions/runs/3418349911/jobs/5690536919

I assume that brew is installing tfsec just for the `ubuntu` user, but then we're trying to run it as a different user

**Comment by davidlawson83** [comment]
That workflow doesn't appear to be using the AWS self-hosted runners, it's missing a with: run-as:  I'll try on the platform-network repo where I originally came across the issue

**Comment by davidlawson83** [comment]
Just added the full path to tfsec in my branch and re running the check on your failing test

**Comment by davidlawson83** [comment]
So I've tried creating aliases for the root user for tfsec and those work when I log into the runner instance but they still don't appear to work via the workflow, I've updated the tfsec command to run using the full path to the executable and that's now working https://github.com/infinitytracking/platform-network/actions/runs/3427466469/jobs/5713780760

Is this acceptable? @dominicbr @Cuthbert286 @mod-elise

**Pull request merged**
