### PR TITLE
[DOS-269] Scheduled golang version checker workflow

### PR DESCRIPTION
**Pull request by Cuthbert286**
This workflow has two actions: check and cron.

The work on this ticket is just for the cron action. The check steps may be added in the future.

### CODE REVIEW

**Comment by JCradock** [comment]
@Cuthbert286 Looks good, do we have an example of an action successfully using this?

**Comment by Cuthbert286** [comment]
> @Cuthbert286 Looks good, do we have an example of an action successfully using this?

An example of this working `without` the scheduled cron time can be seen at https://github.com/infinitytracking/identity-service/actions/runs/3312753843/jobs/5469886554

This ran twice, this first time it created https://github.com/infinitytracking/identity-service/pull/60
The second time the PR creation was skipped.

The below will be added to each repo to make this run on a schedule (also reference to `main` branch once this is deployed):

on:
  schedule:
    - cron: "0 8 * * 1"  # Every Monday at 08:00

**Comment by JCradock** [comment]
Happy with the workflow, can we add a `body:` argument to the `create-pull-request` action to remove the default comment: https://github.com/infinitytracking/identity-service/pull/60#issue-1420765945. Either set it to nothing or set it to the same as the title.

**Comment by Cuthbert286** [comment]
The new `Add Golang version out of date comment` has been added to this. An example of what the comment block looks like can be seen on DOS-269.

**Review by dominicbr — APPROVED** [review]

**Pull request merged**
